services:
  db_livro_de_receitas:
    image: postgres
    container_name: db_livro_de_receitas
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg_livro_de_receitas:/var/lib/postgresql/data

  node_app_livro_de_receitas:
    container_name: livro_de_receitas
    build: .
    ports:
      - 4002:4000
    depends_on:
      - db_livro_de_receitas
    env_file:
      - .env

volumes:
  pg_livro_de_receitas:
