services:
  db_livro_de_receitas:
    image: mongo
    container_name: db_livro_de_receitas
    restart: always
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

  node_app_livro_de_receitas:
    container_name: livro_de_receitas
    build: .
    ports:
      - 4002:4000
    depends_on:
      - db_livro_de_receitas
    env_file:
      - .env
